[#ftl]
[@b.head/]
[@b.form name="studentBedSearchForm"  action="!search" target="studentBedlist" title="ui.searchForm" theme="search"]
    [@b.textfield label="年级" name="studentBed.student.grade" value=year/]
    [@b.textfield label="学号" name="studentBed.student.code"/]
    [@b.textfield label="姓名" name="studentBed.student.name"/]
    [@b.select label="是否入住" name="hasBed" items={'1':'是','0':'否'}/]
[/@]
[@b.div id="studentBedlist" href="!search?studentBed.year=${year}" /]
[@b.foot/]