[#ftl]
[@b.head/]
[@b.grid  items=studentBeds var="studentBed"]
    [@b.gridbar]
    bar.addItem("${b.text("action.export")}",action.exportData("student.code:学号,student.name:姓名,student.gender.name:性别,student.department.name:学院,student.major.name:专业,student.adminClass.name:班级,bed.room.building.name:楼栋,bed.room.name:宿舍,bed.name:床位",null,"&fileName=学生入住信息"));
    [/@]
    [@b.row align="center"]
        [@b.boxcol/]
        [@b.col property="student.code" title="学号" /]
        [@b.col property="student.name" title="姓名" /]
        [@b.col property="student.gender.name" title="性别" /]
        [@b.col property="student.department.name" title="学院" /]
        [@b.col property="student.major.name" title="专业" /]
        [@b.col property="student.adminClass.name" title="班级" /]
        [@b.col property="bed.room.building.name" title="楼栋" /]
        [@b.col property="bed.room.name" title="宿舍" /]
        [@b.col property="bed.name" title="床位" /]
    [/@]
[/@]
[@b.form action="studentBed-print" class="studentBedPrintForm" target="_blank"]
<input type="hidden" name="method" value="" class="method"/>
[/@]
[@b.foot/]