[#ftl]
[@b.head/]
[@b.toolbar title="${(dormBed.bedInfo)!}历史记录"]bar.addBack();[/@]
[@b.grid  items=dormBed.bedLogs var="log" sortable="false"]
	[@b.row]
		[@b.col title="学年学期" property="teachCalendar.yearTerm" align="center"/]
		[@b.col title="学号" property="student.code" align="center"/]
		[@b.col title="姓名" property="student.name" align="center"/]
		[@b.col title="学院" property="student.department.name" align="center"/]
		[@b.col title="年级" property="student.grade" align="center"/]
		[@b.col title="班级" property="student.adminClass.name" align="center"/]
		[@b.col title="辅导员" property="student.adminClass.classTeacher.name" align="center"/]
		[@b.col title="手机" property="student.phone" align="center"/]
		[@b.col title="入住日期" property="startDate" align="center"/]
		[@b.col title="退宿日期" property="endDate" align="center"/]
	[/@]
[/@]
[@b.foot/]