[#ftl]
[@b.head/]
[@b.toolbar title="床位信息"]bar.addBack();[/@]
[@b.form title="床位信息" theme="info" ]
	[@b.textfield label="所属校区" value="${(dormBed.room.floor.building.zone.campus.name)!}"/]
	[@b.textfield label="宿舍区" value="${(dormBed.room.floor.building.zone.name)!}"/]
	[@b.textfield label="宿舍楼" value="${(dormBed.room.floor.building.name)!}"/]
	[@b.textfield label="楼层" value="${(dormBed.room.floor.name)!}"/]
	[@b.textfield label="宿寝室" value="${(dormBed.room.name)!}"/]
	[@b.textfield label="床位号" value="${(dormBed.name)!}"/]
	[@b.textfield label="床位编号" value="${(dormBed.code)!}"/]
	[@b.textfield label="面向层次" value="${(dormBed.education.name)!}"/]
	[@b.textfield label="租金" value="${(dormBed.room.rent)!}"/]
	[@b.textfield label="床位空闲状态" value="${(dormBed.state)!}"/]
	[@b.textfield label="学号" value="${(dormBed.student.code)!}"/]
	[@b.textfield label="姓名" value="${(dormBed.student.name)!}"/]
	[@b.textfield label="学院" value="${(dormBed.student.department.name)!}"/]
	[@b.textfield label="班级" value="${(dormBed.student.adminClass.name)!}"/]
	[@b.textfield label="辅导员" value="${(dormBed.student.adminClass.classTeacher.name)!}"/]
	[@b.textfield label="手机" value="${(dormBed.student.phone)!}"/]
	[@b.textfield label="是否可用" value=(dormBed.enabled?string("是","否")) /]
	[@b.textfield label="备注" value="${(dormBed.remark)!}" /]
[/@]
[@b.foot/]