[#ftl]
[#import "/template/form/utils.ftl" as fu/]
[@b.head/]
[@b.toolbar title="学生请假信息"]bar.addBack();[/@]
[@b.form action="!edit" theme="info"]
    [@b.field label="学号"][@fu.text]${(studentLeave.student.code)!}[/@][/@]
    [@b.field label="姓名"][@fu.text]${(studentLeave.student.name)!}[/@][/@]
    [@b.field label="性别"][@fu.text]${(studentLeave.student.gender.name)!}[/@][/@]
    [@b.field label="院系"][@fu.text]${(studentLeave.student.department.name)!}[/@][/@]
    [@b.field label="专业"][@fu.text]${(studentLeave.student.major.name)!}[/@][/@]
    [@b.field label="班级"][@fu.text]${(studentLeave.student.adminClass.name)!}[/@][/@]
    [@b.datepicker label="请假开始日期" name="studentLeave.startDate" value=studentLeave.startDate format="date" required="true"/]
    [@b.textfield label="请假天数" name="studentLeave.days" value="${studentLeave.days!}" required="true" maxlength="2" iclass="v_integer"/]
    [@b.textarea label="请假原因" name="studentLeave.reason" value="${studentLeave.reason!}" required="true" maxlength="100"/]
    [#if studentLeave.id??]
        [@b.radios label="状态" name="studentLeave.state" value=(studentLeave.state)! items="已销假:已销假,未销假:未销假"/]
    [/#if]
[/@]
[@b.foot/]