[#ftl]
[@b.head/]
[#assign enrollName = "" /]
[#list ac.enrolls as enroll]
	[#assign enrollName = enrollName+enroll.name /]
	[#if enroll_has_next]
		[#assign enrollName = enrollName+"、" /]
	[/#if]
[/#list]
[@b.form name="userForm" id="userForm" action="!addStudentClass?adminClass.id=${ac.id!}"]
	[@b.toolbar title="${(ac.name)!} ${(enrollName)!} 添加学生"]bar.addBack();[/@]
	[@b.grid  items=students var="student" sortable="false" filterable="true"]
	    [@b.gridbar]
	    	bar.addItem("添加",action.multi("saveStudentClass"));
	    [/@]
	    [@b.row align="center"]
	    	[@b.boxcol width="4%"/]
	       	[@b.col property="code" title="学号" /]
	        [@b.col property="name" title="姓名" /]
	        [@b.col property="department.name" title="院系" /]
	        [@b.col property="major.name" title="专业" /]
	        [@b.col property="education.name" title="学历层次" /]
	        [@b.col property="enrollType.name" title="招生类型" /]
			[@b.col property="cardcode" title="身份证号" /]
			[@b.col property="trainType.name" title="培养类型" /]
			[@b.col property="graduateSchool" title="毕业学校" /]
	    [/@]
	[/@]
[/@]
[@b.foot/]