[#ftl]
[@b.head/]
[@b.form action="!search" title="ui.searchForm" target="adminClassAllocList" theme="search"]	
	[@b.textfield label="年级" name="adminClass.grade" value="${grade!}"/]
	[@b.textfields names="adminClass.code;班级代码"/]
	[@b.textfields names="adminClass.name;班级名称"/]
	[@b.select id="departmentId" name="adminClass.department.id" label="所属学院" items=departments /]
	[@b.select id="majorId" name="adminClass.major.id" label="所属专业" items=majors empty=""/]
	[@b.textfields names="adminClass.instructor.code;辅导员工号"/]
	[@b.textfields names="adminClass.instructor.name;辅导员姓名"/]
	[@b.select name="enrollTypeId" label="招生类型" items=enrollTypes /]
[/@]
[@b.div href="!search?adminClass.grade=${grade!}" id="adminClassAllocList" class="adminClassAllocList"/]
[@b.foot/]
<script type="text/javascript" src="${base}/static/scripts/product/cascadeMajor.js"></script>