[#ftl]
[@b.head/]
[@b.toolbar title="${(ac.name)!} 学生名单"]bar.addBack();[/@]
[@b.grid  items=students var="student"]
    [@b.gridbar]
    window.stuentAction = action;
    [#--bar.addItem("编学号",action.method("generateCode"));--]
    [#if students?size < ac.num]
    	bar.addItem("添加",action.method("addStudentClass",null));
    [/#if]
    bar.addItem("删除",action.multi("removeStudentClass","您是否确认要删除选中的数据?"));
    [/@]
    [@b.row align="center"]
    	[@b.boxcol width="4%" /]
       	[@b.col property="code" title="学号" /]
        [@b.col property="name" title="姓名" /]
        [@b.col property="department.name" title="院系" /]
        [@b.col property="major.name" title="专业" /]
        [@b.col property="education.name" title="学历层次" /]
        [@b.col property="enrollType.name" title="招生类型" /]
        [@b.col property="cardcode" title="身份证号" /]
        [@b.col property="trainType.name" title="培养类型" /]
        [@b.col property="graduateSchool" title="毕业学校" /]
    [/@]
[/@]
[@b.foot/]