[#ftl]
[@b.head/]
[@b.toolbar title=title!"行政区划代码" entityId=dictData.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
    [@b.textfield label="代码"name="dictData.gbxb" value="${dictData.gbxb!}" required="true" maxlength="50"/]
    [@b.textfield label="名称"name="dictData.name" value="${dictData.name!}" required="true" maxlength="50"/]
    [@b.radios label="状态"  name="dictData.enabled" value=dictData.enabled items="1:启用,0:禁用"/]
    [@b.formfoot]
    <input type="hidden" name="dictData.id" value="${dictData.id!}"/>
        [@b.redirectParams/]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]