[#ftl]
[@b.head/]
[@b.form name="studentSearchForm"  action="!search?orderBy=code" target="studentList" title="ui.searchForm" theme="search"]
    [@b.textfield label="年份" name="student.grade" value=year/]
    [@b.textfield label="学号" name="student.code"/]
    [@b.textfield label="姓名" name="student.name"/]
[/@]
[@b.div id="studentList" href="!search?student.grade=${year}&orderBy=code" /]
[@b.foot/]