[#ftl]
[@b.head/]
[@b.grid  items=students var="student"]
    [@b.gridbar]
    bar.addItem("导出",action.exportData("code:考生号,name:姓名,enrollType.name:招生类别,major.name:专业,info.accommodationed:是否住宿,cardType:证件类型,cardcode:证件号码,birthday:出生日期,gender.name:性别,country:国家地区,home.nativePlace:籍贯,info.politicalStatus.name:政治面貌,info.nation.name:民族,info.hmto:港澳台侨胞,info.health.name:健康状况,home.domicilePlace:户口所在地,enrollProvince.name:生源地-省份/自治区,enrollCity.name:生源地-城市/地区,enrollCounty.name:生源地-区县,graduateSchool:毕业学校,info.midExamScore:中考分数,phone:手机号码,telephone:联系电话,contact.province.name:通讯地址-省份/自治区,contact.city.name:通讯地址-城市/地区,contact.county.name:通讯地址-区县,contact.address:通讯地址,contact.zipcode:邮政编码,home.phone:家庭电话,home.contact:家庭联系人,home.address:家庭地址,home.province.name:家庭-省份/自治区,home.city.name:家庭-城市/地区,home.county.name:家庭-区县,info.nameUsed:曾用名,contact.qq:QQ号,contact.wechat:微信号,email:常用信箱,info.specialSkill:特长", null,"&fileName=student"));
    [/@]

    [@b.row align="center" sortable="false"]
        [@b.boxcol width="1"/]
        [@b.col title="考生号" property="code"/]
        [@b.col title="姓名" property="name"]
            [@b.a href="!info?student.id=${student.id}"]${student.name}[/@]
        [/@]
        [@b.col title="是否住宿" property="info.accommodationed" sortable="false"]
            [#if student.info.accommodationed??]
                [@c.boolean student.info.accommodationed/]
            [/#if]
        [/@]
        [@b.col title="证件号码" property="cardcode"/]
        [@b.col title="性别" property="gender.name"/]
        [@b.col title="民族" property="info.nation.name" sortable="false"/]
        [@b.col title="户口所在地地址" property="home.domicilePlaceAddress"/]
        [@b.col title="最后毕业学校" property="graduateSchool"/]
        [@b.col title="手机号码" property="phone"/]
        [@b.col title="通讯地址" property="contact.address"/]
        [@b.col title="户口所在地" property="home.domicilePlace"/]
        [@b.col title="常用信箱" property="email"/]
        [@b.col title="特长" property="info.specialSkill" sortable="false"/]
    [/@]
[/@]
[@b.foot/]