[#ftl]
[@b.head/]
[@b.form action="!search" title="ui.searchForm" target="processBatchList" theme="search"]
    [@b.select name="processBatch.year" value="${(processYear)!}" label="学年度" items=years empty="..." option="year,year"/]
    [@b.textfields names="processBatch.name;批次名称"/]
    [@b.select name="processBatch.started" label="状态" items={'1':'启动','0':'停止'}/]
    [@b.select name="processBatch.submited" label="提交状态" items={'1':'已提交','0':'未提交'}/]
[/@]
[@b.div href="!search?orderBy=processBatch.name" id="processBatchList" class="dataList"/]
[@b.foot/]
