[#ftl]
[@b.head/]
[@b.toolbar title="军训服装情况"]bar.addBack();[/@]
[@b.form action="!search" theme="info"]
    [@b.textfield label="学号" value=(clothesStudent.student.code)!"" /]
    [@b.textfield label="姓名" value=(clothesStudent.student.name)!"" /]
    [@b.textfield label="院系" value=(clothesStudent.student.department.name)!"" /]
    [@b.textfield label="专业" value=(clothesStudent.student.major.name)!"" /]
    [@b.textfield label="班级" value=(clothesStudent.student.adminClass.name)!"" /]
[#--    [@b.textfield label="身高（cm）" value=(clothesStudent.height)!"" /]
    [@b.textfield label="体重（kg）" value=(clothesStudent.weight)!"" /]
    [@b.textfield label="胸围（cm）" value=(clothesStudent.bust)!"" /]
    [@b.textfield label="腰围（cm）" value=(clothesStudent.waist)!"" /]
    [@b.textfield label="臀围（cm）" value=(clothesStudent.hip)!"" /]--]
    [@b.textfield label="服装尺码" value=(clothesStudent.clothesSize)!"" /]
    [@b.textfield label="鞋子尺码" value=(clothesStudent.shoesSize)!"" /]
[/@]
[@b.foot/]