[#ftl]
[@b.head/]
[@b.toolbar title="报到情况"]bar.addBack();[/@]
[@b.form action="!search" theme="info"]
    [@b.textfield label="学号" value=(stationStudent.student.code)!"" /]
    [@b.textfield label="姓名" value=(stationStudent.student.name)!"" /]
    [@b.textfield label="院系" value=(stationStudent.student.department.name)!"" /]
    [@b.textfield label="专业" value=(stationStudent.student.major.name)!"" /]
    [@b.textfield label="班级" value=(stationStudent.student.adminClass.name)!"" /]
    [@b.textfield label="到达日期" value=(stationStudent.arriveDate?date)!"" /]
    [@b.textfield label="是否可以按时报到" value=(stationStudent.intime?string("是", "否"))!"" /]
    [#if true == (stationStudent.intime)!false]
        [@b.textfield label="交通工具选择" value=(stationStudent.vehicle.name)!"" /]
        [@b.textfield label="是否接站" value=(stationStudent.needPickup?string("是", "否"))!"" /]
        [@b.textfield label="到达时间" value=(stationStudent.arriveTime)!"" /]
        [@b.textfield label="到达站" value=(stationStudent.station)!"" /]
        [@b.textfield label="陪同人数" value=(stationStudent.num)!"" /]
    [#else]
        [#if stationStudent.reason??]
            [@b.textfield label="不按时报到原因" value=(stationStudent.reason)!"" /]
        [/#if]
    [/#if]
[/@]
[@b.foot/]