[#ftl]
[@b.head/]
[@b.toolbar title="生活物品" entityId=supplies.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
    [@b.textfield label="代码" name="supplies.code" value="${supplies.code!}" required="true" maxlength="100"/]
    [@b.textfield label="名称" name="supplies.name" value="${supplies.name!}" required="true" maxlength="100"/]
    [@b.textfield label="规格" name="supplies.spec" value="${supplies.spec!}" maxlength="100"/]
    [@b.textfield label="价格" name="supplies.price" value="${supplies.price!}" maxlength="100"/]
    [@b.textfield label="默认数量" name="supplies.num" value="${supplies.num!}" required="true" maxlength="3" class="v_integer"/]
    [@b.textfield label="最大数量" name="supplies.maxNum" value="${supplies.maxNum!}" required="true" maxlength="3" class="v_integer"/]
    [@b.textfield label="备注" name="supplies.remark" value="${supplies.remark!}" maxlength="100"/]
    [@b.radios label="类型" name="supplies.type.id" value=(supplies.type.id)!0 items=types required="true" option="id,name"/]
    [@b.radios label="状态" name="supplies.enabled" value=supplies.enabled items="1:启用,0:禁用"/]
    [@b.formfoot]
	<input type="hidden" name="supplies.id" value="${supplies.id!}"/>
        [@b.redirectParams/]
        [@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]