[#ftl]
[#include "../comm/lib.ftl"/]
[@b.head/]
[@b.grid  items=students var="student"]
	[@b.gridbar]
		window.stuentAction = action;
		bar.addItem("批量办理",action.multi("handleBatch",null,"batchId=${batchId}&itemId=${itemId}"), "fa-edit", "blue");
	[/@]
	[@b.row align="center"]
		[@b.boxcol/]
		[@b.col title="数字ID" property="serial"/]
		[@b.col title="学院" property="department.name"/]
		[@b.col title="专业" property="major.name"/]
		[@b.col title="班级" property="adminClass.name"/]
		[@b.col title="学号" property="code"/]
		[@b.col title="姓名" property="name"/]
		[@b.col title="性别" property="gender.name"/]
		[@b.col title="身份证号" property="cardcode"/]
		[@b.col title="操作"]
			[@b.a href="!edit?code=${(student.cardcode)!}&batchId=${batchId}&itemId=${itemId}"]办理[/@]
		[/@]
	[/@]
[/@]
[@b.foot/]