[#ftl]
[#import "/template/form/utils.ftl" as fu/]
[@b.head/]
[@b.form action="!edit" title="参数设置" theme="form"]
    [@b.static label="当前年度"]${(systemConfig.year)!}[/@]
    [@b.static label="是否有院系"]${(systemConfig.hasDepartment?string("是", "否"))!}[/@]
    [@b.static label="部门名称"]${(systemConfig.departmentName)!}[/@]
    [@b.formfoot]
        [@b.submit value="修改"/]
    [/@]
[/@]
[@b.foot/]