[#ftl]
[@b.head/]
[@b.form name="financeStudentItemSearchForm"  action="!search" target="financeStudentItemlist" title="ui.searchForm" theme="search"]
    [@b.textfield label="年份" name="financeStudentItem.financeStudent.year" value=year/]
    [@b.textfield label="学号" name="financeStudentItem.financeStudent.student.code"/]
    [@b.textfield label="姓名" name="financeStudentItem.financeStudent.student.name"/]
    [@b.select label="缴费项目" name="financeStudentItem.item.id" items=items/]
    [@b.select label="缴费状态" name="status" items={'1':'交清','2':'部分交清','3':'未交清'}/]
[/@]
[@b.div id="financeStudentItemlist" href="!search?financeStudentItem.financeStudent.year=${year}" /]
[@b.foot/]