[#ftl]
[@b.head/]
[#include "../nav.ftl"/]
	[@b.form action="!search?orderBy=adminClass.code" title="ui.searchForm" target="adminClassList" theme="search"]	
		[@b.textfields names="adminClass.code;班级代码"/]
		[@b.textfields names="adminClass.name;班级名称"/]
		[@b.textfields names="adminClass.grade;年级"/]
		[@b.select id="departmentId" name="adminClass.department.id" label="所属学院" items=departs?sort_by("code")/]
		[@b.select id="majorId" name="adminClass.major.id" label="所属专业" items=majors empty=""/]
		[@b.textfields names="instructorCode;辅导员工号"/]
		[@b.textfields names="instructorName;辅导员姓名"/]
		[@b.select name="enrollTypeId" label="招生类型" items=enrollTypes /]
		[@b.select name="adminClass.enabled" label="是否可用" value="1" items={'1':'是','0':'否'}/]
	[/@]
	[@b.div href="!search?orderBy=adminClass.code&adminClass.enabled=1" id="adminClassList" class="dataList"/]
[@b.foot/]
<script type="text/javascript" src="${base}/static/scripts/product/cascadeMajor.js"></script>
