[#ftl]
[@b.head/]
[@b.toolbar title="班级"]bar.addBack();[/@]
[@b.form action="!save" title="班级信息" theme="info"]
	[@b.textfield label="班级代码" name="adminClass.code" value="${adminClass.code!}"/]
	[@b.textfield label="班级名称" name="adminClass.name" value="${adminClass.name!}"/]
	[@b.textfield label="年级" name="adminClass.grade" value="${adminClass.grade!}"/]
	[@b.textfield label="学院" name="adminClass.department" value="${(adminClass.department.name)!}" /]
	[@b.textfield label="所属专业" name="adminClass.major" value="${(adminClass.major.name)!}"/]
	[@b.field label="招生类型" ]
		[#list adminClass.enrolls as enroll]${(enroll.name)!}[/#list]
	[/@]
	[@b.field label="辅导员" ]
		[#if adminClass.instructor??]${(adminClass.instructor.name)!}(${(adminClass.instructor.code)!})[/#if]
	[/@]
	[@b.textfield label="班级人数" name="adminClass.num" value="${(adminClass.num)!}"/]
    [@b.radios label="是否可用"  name="adminClass.enabled" value=adminClass.enabled items="1:是,0:否"/]	
[/@]
[@b.foot/]
