[#ftl]
[#import "/template/info/comm.ftl" as ic/]
[@b.head/]
[@b.toolbar title="信息详细"]bar.addBack();[/@]
[@b.form theme="info"]
    [@b.field label="所属栏目"]
        [@ic.text]
            [#if (content.column.parent)??]${(content.column.parent.name)} >> [/#if]${(content.column.name)!}
        [/@]
    [/@]
    [@b.textfield label="标题" name="content.title" value="${content.title!}" required="true" maxlength="100"/]
    [@b.datepicker label="发布日期" name="content.publishTime" value=content.publishTime required="true"/]
    [@b.ueditor label="内容" name="content.content" value=content.content required="true"/]
    [@b.radios label="是否置顶"  name="content.stick" value=content.stick items="1:是,0:否"/]
    [@b.radios label="是否发布"  name="content.enabled" value=content.enabled items="1:是,0:否"/]
[/@]
[@b.foot/]