[#ftl]
[@b.head/]
[@b.grid  items=contents var="content"]
    [@b.gridbar]
	bar.addItem("${b.text("action.new")}",action.add());
	bar.addItem("${b.text("action.modify")}",action.edit());
	bar.addItem("${b.text("action.delete")}",action.remove());
    [/@]
    [@b.row align="center"]
        [@b.boxcol/]
        [@b.col width="10%" title="一级栏目" align="center"]
            [#if (content.column.parent)??]${(content.column.parent.name)!}[#else ]${(content.column.name)!}[/#if]
        [/@]
        [@b.col width="10%" title="二级栏目" align="center"]
            [#if (content.column.parent)??]${(content.column.name)!}[/#if]
        [/@]
        [@b.col width="40%" property="title" title="标题" align="left"]
            [@b.a href="!info?content.id=${content.id}"]${(content.title)!}[/@]
        [/@]
        [@b.col width="10%" property="enabled" title="是否发布"]
            [@c.boolean content.enabled/]
        [/@]
        [@b.col width="10%" property="stick" title="是否置顶"]
            [@c.boolean content.stick/]
        [/@]
        [@b.col width="10%" property="user.fullname" title="发布人"/]
        [@b.col width="10%" property="publishTime" title="发布时间"/]
    [/@]
[/@]
[@b.foot/]