[#ftl]
[@b.head/]
[@b.toolbar title="${(planName)!}——住宿学生名单"]bar.addBack();[/@]
[@b.grid  items=dormPlanBeds var="dormPlanBed"]
	<div class="btn-toolbar margin-bottom-10" >
		<div class="btn-group"><a href="${b.url("!exportExcelStdNum")}&majorAccomPlanId=${majorAccomPlanId}" target="_blank" class="btn green"><i class="fa fa-file-excel-o"></i>&nbsp;导出</a></div></div>

[#--	[@b.gridbar]--]
[#--	[/@]--]
	[@b.row]
		[@b.col title="学号" property="student.code" align="center"/]
		[@b.col title="姓名" property="student.name" align="center" align="center"/]
		[@b.col title="性别" property="student.gender.name" align="center"/]
		[@b.col title="年级" property="student.grade" align="center"/]
		[@b.col title="学院" property="student.department.name" align="center"/]
		[@b.col title="班级" property="student.adminClass.name" align="center"/]
		[@b.col title="学历层次" property="student.education.name" align="center"/]
		[@b.col title="入学年月" property="student.enrollmentDate" align="center"/]
		[@b.col title="校区" property="student.campus.name" align="center"/]
				[@b.col title="宿舍区" property="bed.room.building.zone.name" align="center"/]
		[@b.col title="楼栋" property="bed.room.building.name" align="center"/]
		[@b.col title="宿舍" property="bed.room.name" align="center"/]
		[@b.col title="床位" property="bed.name" align="center"/]
		[@b.col title="租金" property="bed.room.rent" align="center"/]
	[/@]
[/@]
[@b.foot/]