[#ftl]
[@b.head/]
	[@b.form action="!search" title="ui.searchForm" target="majorAccomPlanList" theme="search"]	
		[@b.select label="学年度" name="majorAccomPlan.dormPlan.year" items=years value=(curYear.year)! options="year,year"/]
		[@b.select label="住宿计划" name="majorAccomPlan.dormPlan.id" value=(dormPlan.id)! items=dormPlans/]
		[@b.select id="departmentId" name="majorAccomPlan.major.department.id" label="院（系）" items=departments option="id,name"/]
		[@b.select id="majorId" name="majorAccomPlan.major.id" label="专业" items=majorList option="id,name"/]
		[@b.select name="majorAccomPlan.gender" label="寝室面向性别" items={'男':'男','女':'女'}/]
		[@b.select label="是否确认" name="majorAccomPlan.confirm" items={'1':'已确认','0':'未确认'}/]
		[@b.select label="是否发布" name="majorAccomPlan.deptAccomPlan.finish" items={'1':'已发布','0':'未发布'}/]
	[/@]
	[@b.div href="!search?majorAccomPlan.dormPlan.year=${(curYear.year)!}&orderby=majorAccomPlan.major.code,majorAccomPlan.gender" id="majorAccomPlanList" major="majorAccomPlanList"/]
[@b.foot/]
<script type="text/javascript" src="${base}/static/scripts/product/cascadeMajor.js"></script>