[#ftl]
[#include "/template/list/comm.ftl"]	
[@b.head/]
[@b.toolbar title="专业住宿计划信息"]bar.addBack();[/@]
[@b.form theme="info"]
	[@b.textfield label="年份" value="${(majorAccomPlan.dormPlan.year)!}"/]
    [@b.textfield label="计划" value="${(majorAccomPlan.dormPlan.name)!}"/]
    [@b.textfield label="院（系）代码" value="${(majorAccomPlan.major.department.code)!}"/]
    [@b.textfield label="院（系）名称" value="${(majorAccomPlan.major.department.name)!}"/]
    [@b.textfield label="专业代码" value="${(majorAccomPlan.major.code)!}"/]
    [@b.textfield label="专业名称" value="${(majorAccomPlan.major.name)!}"/]
    [@b.textfield label="寝室面向性别" value="${(majorAccomPlan.gender)!}"/]
    [@b.textfield label="计划人数" value="${(majorAccomPlan.planNum)!}"/]
    [@b.textfield label="安排床位数" value="${(majorAccomPlan.allotNum)!}"/]
    [@b.textfield label="已安排学生" value="${(majorAccomPlan.stdNum)!}"/]
    [@b.textfield label="备注" value="${(majorAccomPlan.remark)!}"/]
[/@]
[@b.foot/]