[#ftl]
[@b.head/]
[@b.form name="studentPrintViewSearchForm"  action="!search" target="studentPrintViewlist" title="ui.searchForm" theme="search"]
    [@b.textfield label="年级" name="studentPrintView.student.grade" value=grade/]
    [@b.textfield label="学号" name="studentPrintView.student.code"/]
    [@b.textfield label="姓名" name="studentPrintView.student.name"/]
    [#--[@b.select label="性别" name="studentPrintView.student.gender.id" items=genders/]--]
    [@b.select label="招生类别" name="studentPrintView.student.enrollType.id" items=enrollTypes/]
    [@b.select label="培养类型" name="studentPrintView.student.trainType.id" items=trainTypes/]
    [@b.select id="departmentId" name="studentPrintView.student.department.id" label="所属学院" items=departs?sort_by("code")/]
    [@b.select id="majorId" name="studentPrintView.student.major.id" label="所属专业" items=majors empty=""/]
    [@b.textfield label="毕业学校" name="studentPrintView.student.graduateSchool"/]
    [@b.select label="省份" name="studentPrintView.student.enrollProvince.id" items=provinces iclass="s_province"/]
    [@b.select label="通知书是否打印" name="studentPrintView.printNotice" items={'1':'是','0':'否'} value="0"/]
    [@b.select label="封面是否打印" name="studentPrintView.printFace" items={'1':'是','0':'否'} value="0"/]
[/@]
[@b.div id="studentPrintViewlist" href="!search?studentPrintView.student.grade=${grade}&studentPrintView.printNotice=0&studentPrintView.printFace=0" /]
[@b.foot/]
<script type="text/javascript" src="${base}/static/scripts/product/cascadeMajor.js"></script>