[#ftl]
[#include "../comm/macro.ftl"/]
[#import "/template/form/utils.ftl" as fu/]
[@index code="02"]
<h3 class="caption">报到情况</h3>
<div class="row">
    [@b.form action="!edit" theme="form" boxClass="xxx"]
        [#if stationStudent??]
            [@b.field label="到达日期"]
                [@fu.text]${(stationStudent.arriveDate?date)!}[/@]
            [/@]
            [@b.field label="是否按时报到"]
                [@fu.text]${(stationStudent.intime?string("是", "否"))!}[/@]
            [/@]
            [#if true == (stationStudent.intime)!false]
                [@b.field label="是否需要接站"]
                    [@fu.text]${(stationStudent.needPickup?string("是", "否"))!}[/@]
                [/@]
                [@b.field label="到达时间"]
                    [@fu.text]${(stationStudent.arriveTime)!}[/@]
                [/@]
                [@b.field label="交通工具"]
                    [@fu.text]${(stationStudent.vehicle.name)!}[/@]
                [/@]
                [@b.field label="到达站"]
                    [@fu.text]${(stationStudent.station)!}[/@]
                [/@]
                [@b.field label="陪同人数"]
                    [@fu.text]${(stationStudent.num)!}[/@]
                [/@]
            [#else]
                [@b.field label="不按时报到原因"]
                    [@fu.text]${(stationStudent.reason)!}[/@]
                [/@]
            [/#if]
        [#else]
            [@emptyMessage/]
        [/#if]
        [#if switch?? && switch.editable]
            [@b.formfoot]
                <a href="${b.url("!edit")}" class="btn blue">修改</a>
            [/@]
        [/#if]
    [/@]
</div>
[/@index]
