[#ftl]
[@b.head/]
[@b.toolbar title="学生信息" entityId=student.id!0]bar.addBack();[/@]
[@b.form action="!save" title="学生信息" theme="form"]
	[@b.classConfig configs=formConfig]
		[@b.static label="年级"]${(student.grade)!}[/@b.static]
		[@b.static label="院系"]${(student.department.name)!}[/@b.static]
		[@b.static label="专业"]${(student.major.name)!}[/@b.static]
		[@b.select label="班级" name="student.adminClass.id" value=(student.adminClass.id)! items=adminClasses/]
		[@b.textfield label="学号" name="student.code" value="${student.code!}" maxlength="100" /]
		[@b.static label="姓名"]${(student.name)!}[/@b.static]
		[@b.static label="性别"]${(student.gender.name)!}[/@b.static]
		[@b.textfield label="备注" name="student.remark" value="${student.remark!}" maxlength="100" /]
	[/@]
	[@b.formfoot]
		[@b.redirectParams/]
		[@b.submit value="action.submit" /]
		<input type="hidden" name="student.id" value="${student.id!}"/>
	[/@]
[/@]
[@b.foot/]