[#ftl]
[@b.head/]
[@b.toolbar title="学生信息" entityId=student.id!0]bar.addBack();[/@]
[@b.form action="!info" title="学生信息" theme="form"]
	[@b.classConfig configs=formConfig]
		[@b.static label="年级"]${(student.grade)!}[/@b.static]
		[@b.static label="院系"]${(student.department.name)!}[/@b.static]
		[@b.static label="专业"]${(student.major.name)!}[/@b.static]
		[@b.static label="班级"]${(student.adminClass.name)!}[/@b.static]
		[@b.static label="学号"]${(student.code)!}[/@b.static]
		[@b.static label="姓名"]${(student.name)!}[/@b.static]
		[@b.static label="性别"]${(student.gender.name)!}[/@b.static]
		[@b.static label="备注"]${(student.remark)!}[/@b.static]
	[/@]
[/@]
[@b.foot/]