[#ftl]
[#import "/template/form/utils.ftl" as fu/]
[@b.head/]
[@b.form action="!edit" title="参数设置" theme="info"]
    [@b.static label="学生密码生成方式"]${(prepareConfig.passwordType.name)!}[/@]
    [@b.formfoot]
        [@b.a href="!edit" class="btn blue"]修改[/@]
    [/@]
[/@]
[@b.foot/]