[#ftl]
[@b.head/]
[@b.form name="studentFamilySearchForm"  action="!search?orderBy=student.code" target="studentFamilyList" title="ui.searchForm" theme="search"]
    [@b.textfield label="年份" name="studentFamily.student.grade" value=year/]
    [@b.textfield label="学号" name="studentFamily.student.code"/]
    [@b.textfield label="姓名" name="studentFamily.student.name"/]
[/@]
[@b.div id="studentFamilyList" href="!search?studentFamily.grade=${year}&orderBy=student.code" /]
[@b.foot/]