[#ftl]
[@b.head/]
[@b.grid  items=studentFamilys var="studentFamily"]
    [@b.gridbar]
    [#--bar.addItem("导出",action.exportData("student.code:考生号,student.name:学生姓名,student.enrollType.name:招生类别,student.major.name:专业,title:家庭成员称谓,name:家庭成员姓名,phone:联系电话,age2:年龄,unit:工作单位及地址,post:职位,political.name:政治面貌", null,"&fileName=studentFamily"));--]
    bar.addItem("导出",action.exportData("student.code:考生号,student.name:学生姓名,student.enrollType.name:招生类别,student.major.name:专业,title:家庭成员称谓,name:家庭成员姓名,phone:联系电话,age2:年龄,unit:工作单位,political.name:政治面貌", null,"&fileName=studentFamily"));
    [/@]

    [@b.row align="center"]
        [@b.boxcol width="1"/]
        [@b.col title="考生号" property="student.code"/]
        [@b.col title="学生姓名" property="student.name"/]
        [@b.col title="家庭成员称谓" property="title"/]
        [@b.col title="家庭成员姓名" property="name"/]
        [@b.col title="年龄" property="age2"/]
        [@b.col title="家庭成员联系电话" property="phone"/]
    [/@]
[/@]
[@b.foot/]