[#ftl]
[@b.head/]
[@b.toolbar title="鞋子尺码" entityId=shoesSize.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
    [@b.textfield label="代码" name="shoesSize.code" value="${shoesSize.code!}" required="true" maxlength="30"/]
    [@b.textfield label="尺码" name="shoesSize.name" value="${shoesSize.name!}" required="true" maxlength="30"/]
    [@b.textfield label="脚长" name="shoesSize.footLength" value="${shoesSize.footLength!}" required="true" maxlength="30"/]
    [@b.formfoot]
	<input type="hidden" name="shoesSize.id" value="${shoesSize.id!}"/>
        [@b.redirectParams/]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]