[#ftl]
[@b.head/]
[@b.toolbar title="住宿费用设置"][/@]
[@b.form action="!settingSave" theme="list"]
    [@b.field label="收费标准"]
    [#include "table.ftl"/]
    [/@]
    [@b.formfoot]
        [@b.a href="!edit" class="btn blue"]编辑[/@]
    [/@]
[/@]
[@b.foot/]