[#ftl]
[@b.head/]
[@b.grid  items=studentEnrolls var="studentEnroll"]
    [@b.gridbar]
    bar.addItem("标记为“已注册”", action.multi("registed", null, "registed=1"), "fa-check",  "green-haze");
    bar.addItem("标记为“未注册”", action.multi("registed", null, "registed=0"), "fa-close",  "red");
    bar.addItem("导入",action.method("importForm"));
    bar.addItem("${b.text("action.export")}", action.exportData("招生批次,学号,姓名,身份证号,是否注册",null,"&fileName=学生注册信息"));
    [/@]
    [@b.row align="center"]
        [@b.boxcol width="1%"/]
        [@b.col property="batch.name" title="招生批次" /]
    [#--[@b.col property="grade" title="年级" /]--]
        [#--[@b.col property="student.code" title="学号" /]--]
        [@b.col property="code" title="学号" /]
        [@b.col property="student.name" title="姓名" /]
        [@b.col property="student.gender.name" title="性别" /]
        [@b.col property="student.info.nation.name" title="民族" /]
        [@b.col property="student.phone" title="学生电话" /]
        [@b.col property="student.cardcode" title="身份证号" /]
    [#--[@b.col property="birthday" title="出生年月"]${(student.birthday?string("yyyy-M"))!}[/@]--]
    [#--[@b.col property="schoolName" title="毕业学校" /]--]
    [#--[@b.col property="enrollType.name" title="招生类别" /]--]
    [#--[@b.col property="province.name" title="省" /]--]
    [#--[@b.col property="city.name" title="市" /]--]
    [#--[@b.col property="county.name" title="区县" /]--]
    [#--[@b.col property="fatherPhone" title="父亲电话" /]--]
    [#--[@b.col property="motherPhone" title="母亲电话" /]--]
        [@b.col property="student.registed" title="是否注册" align="center"][@c.boolean studentEnroll.student.registed/][/@]
    [/@]
[/@]
[@b.form action="student-notice-import!importForm" class="studentNoticeImportForm"]
[/@]
[@b.form action="student-enroll-import!importForm" class="studentEnrollImportForm"]
[/@]
[@b.foot/]