[#ftl]
[@b.head/]
[@b.form name="askCommonSearchForm"  action="!search" target="askCommonlist" title="ui.searchForm" theme="search"]
    [@b.textfield label="咨询内容" name="askCommon.content"/]
    [@b.select label="是否置顶" name="askCommon.top" items={'1':'是','0':'否'}/]
    [@b.select label="状态" name="askCommon.enabled" items={'1':'启用','0':'禁用'} value="1"/]
[/@]
[@b.div id="askCommonlist" href="!search" /]
[@b.foot/]