[#ftl]
[@b.head/]
[@b.toolbar title="收费项目" entityId=financeItem.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
	[@b.textfield label="代码"name="financeItem.code" value="${financeItem.code!}" required="true" maxlength="50"/]
	[@b.textfield label="名称"name="financeItem.name" value="${financeItem.name!}" required="true" maxlength="50"/]
	[@b.radios label="是否可缓交"  name="financeItem.delayable" value=financeItem.delayable items="1:是,0:否"/]
	[@b.radios label="是否可贷款"  name="financeItem.loanable" value=financeItem.loanable items="1:是,0:否"/]
	[@b.radios label="状态"  name="financeItem.enabled" value=financeItem.enabled items="1:启用,0:禁用"/]
	[@b.formfoot]
		<input type="hidden" name="financeItem.id" value="${financeItem.id!}" />
		[@b.redirectParams/]
		[@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
	[/@]
[/@]
[@b.foot/]