[#ftl]
[@b.head/]
[@b.grid  items=askStudents var="askStudent"]
    [@b.row]
        [@b.boxcol/]
        [@b.col title="学号" property="student.name" align="center"/]
        [@b.col title="姓名" property="student.fullname" align="center"/]
        [@b.col title="咨询内容" property="content" /]
        [@b.col title="咨询时间" property="createTime" align="center"]
            ${(askStudent.createTime?string("yyyy-MM-dd HH:mm"))}
        [/@]
        [@b.col title="状态" property="status" align="center"]
            [@c.boolean value=(askStudent.status == "已回复") yes="已回复" no="未回复"/]
        [/@]
        [@b.col title="操作" align="center"]
            [@b.a href="!edit?askStudent.id=${askStudent.id}" class="btn btn-primary btn-sm"]回复[/@]
        [/@]
    [/@]
[/@]
[@b.foot/]