[#ftl]
[@b.head/]
[@b.toolbar title="尺码" entityId=clothesSize.id!0]bar.addBack();[/@]
[@b.form action="!save" title="尺码" theme="form"]
    [#if (clothesSize.type.id)??]
        [#if (clothesSize.type.name)??]
            [@b.static label="服装类型"]${(clothesSize.type.name)!}[/@b.static]
        [/#if]
    [#else]
        [@b.select label="服装类型" name="clothesSize.type.id" value=(clothesSize.type.id)!0 items=types/]
    [/#if]
    [@b.textfield label="代码" name="clothesSize.code" value="${clothesSize.code!}" required="true" maxlength="50"/]
    [@b.textfield label="名称" name="clothesSize.name" value="${clothesSize.name!}" required="true" maxlength="50"/]
    [@b.textfield label="值" name="clothesSize.value" value="${clothesSize.value!}" required="true" maxlength="50"/]
    [@b.formfoot]
    <input type="hidden" name="clothesSize.id" value="${clothesSize.id!}"/>
    <input type="hidden" name="clothesSize.type.id" value="${(clothesSize.type.id)!}"/>
        [@b.redirectParams/]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]