[#ftl]
[@b.head/]
[@b.toolbar title="字典数据-查看"]bar.addBack();[/@]
[@b.form action="!search" theme="info"]
    [@b.field label="代码"]${(batch.code)!}[/@]
    [@b.field label="名称"]${(batch.name)!}[/@]
    [@b.field label="英文名称"]${(batch.enName)!}[/@]
    [@b.field label="国标校标"]${(batch.gbxb)!}[/@]
    [@b.field label="字典类型"]${(batch.dictType.name)!}[/@]
    [@b.field label="状态"]${(batch.enabled?string("启用", "禁用"))!}[/@]
[/@]
[@b.foot/]