[#ftl]
[#import "/template/form/utils.ftl" as fu/]
[@b.head/]
[@b.toolbar title="未报到学生原因" entityId=welcomeStudent.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="list"]
    [@b.field label="学号"][@fu.text]${(welcomeStudent.student.code)!}[/@][/@]
    [@b.field label="姓名"][@fu.text]${(welcomeStudent.student.name)!}[/@][/@]
    [@b.field label="性别"][@fu.text]${(welcomeStudent.student.gender.name)!}[/@][/@]
    [@b.field label="院系"][@fu.text]${(welcomeStudent.student.department.name)!}[/@][/@]
    [@b.field label="专业"][@fu.text]${(welcomeStudent.student.major.name)!}[/@][/@]
    [#--[@b.field label="专业方向"][@fu.text]${(welcomeStudent.student.direction.name)!}[/@][/@]--]
    [@b.field label="班级"][@fu.text]${(welcomeStudent.student.adminClass.name)!}[/@][/@]
    [@b.textarea label="未报到原因" name="welcomeStudent.remark" value="${(welcomeStudent.remark)!}" style="width:350px" cols="50" rows="3" maxlength="200" /]
    [@b.formfoot]
    <input type="hidden" name="welcomeStudent.id" value="${welcomeStudent.id!}"/>
    <input type="hidden" name="welcomeStudent.student.id" value="${welcomeStudent.student.id!}"/>
        [@b.redirectParams/]
        [@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]