[#ftl]
[@b.head/]
[@b.form name="welcomeStudentSearchForm"  action="!search" target="welcomeStudentlist" title="ui.searchForm" theme="search"]
    [@b.select label="年级" name="welcomeStudentView.student.grade" value=year items=years/]
    [@b.textfield label="学号" name="welcomeStudentView.student.code"/]
    [@b.textfield label="姓名" name="welcomeStudentView.student.name"/]
    [@b.select label="院系" name="welcomeStudentView.student.department.id" items=departments/]
    [#--[@b.select label="专业" name="student.major.id" iclass="s_major"/]--]
    [#--[@b.select label="专业方向" name="student.direction.id" iclass="s_direction"/]--]
    [#--[@b.select label="未报到原因" name="welcomeStudent.reason.id" items=reasons/]--]
    [@b.select label="处理状态" name="isdone" items={'1':'已处理','0':'未处理'}/]
[/@]
[@b.div id="welcomeStudentlist" href="!search?student.year=${year}" /]
[@b.foot/]