[#ftl]
[@b.head/]
[@b.toolbar title="咨询板块" entityId=askPlate.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
    [@b.textfield label="代码" name="askPlate.code" value="${askPlate.code!}" required="true" maxlength="50"/]
    [@b.textfield label="名称" name="askPlate.name" value="${askPlate.name!}" required="true" maxlength="30"/]
    [@b.radios label="状态"  name="askPlate.enabled" value=askPlate.enabled items="1:启用,0:禁用"/]
    [@b.formfoot]
    <input type="hidden" name="askPlate.id" value="${askPlate.id!}"/>
        [@b.redirectParams/]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]