[#ftl]
[@b.navmenu title="财务数据" target="finance_div"]
    [@ems.guard res="/finance/finance-status"][@b.navitem title="财务缴费" href="/finance/finance-status"/][/@]
    [@ems.guard res="/finance/finance-item"][@b.navitem title="收费项目" href="/finance/finance-item"/][/@]
    [@ems.guard res="/finance/finance-template"][@b.navitem title="财务费用模板" href="/finance/finance-template"/][/@]
    [@ems.guard res="/finance/finance-green"][@b.navitem title="绿色通道类型" href="/finance/finance-green"/][/@]
    [@ems.guard res="/finance/dorm-setting"][@b.navitem title="住宿费用设置" href="/finance/dorm-setting"/][/@]
[/@]
[@b.div id="finance_div"/]