[#ftl]
[#import "/template/yxxt/formUtils.ftl" as fu/]
[@b.head/]
[@b.toolbar title="信息采集开关" entityId=collectSwitch.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
	[#if userid == 1]
		[@b.textfield label="代码" name="collectSwitch.code" value="${collectSwitch.code!}" required="true" maxlength="10"/]
		[@fu.uploadImg label="图标" value=collectSwitch.icon!"" width=50 height=50 dir="collectSwitch"/]
		[@b.textfield label="URL" name="collectSwitch.url" value="${collectSwitch.url!}" required="true" maxlength="200"/]
	[#else]
	[/#if]
	[@b.textfield label="排序" name="collectSwitch.sort" value="${collectSwitch.sort!}" required="true" maxlength="2"/]
	[@b.textfield label="名称" name="collectSwitch.name" value="${collectSwitch.name!}" required="true" maxlength="30"/]
	[@b.textarea label="注意事项" name="collectSwitch.remark" value=(collectSwitch.remark)! cols="50" rows="3"  maxlength="1000"/]
	[@b.startend label="填写开始结束时间"
	name="collectSwitch.startTime,collectSwitch.endTime" required="false,false"
	start=collectSwitch.startTime end=collectSwitch.endTime format="datetime"/]
	[@b.checkboxes label="适用招生类别" name="enrollTypeId" value=collectSwitch.enrollTypes items=enrollTypes/]
	[@b.checkboxes label="适用学历层次" name="educationId" value=collectSwitch.educations items=educations/]
[#--[@b.radios label="是否在线支付"  name="collectSwitch.payment" value=collectSwitch.payment items="1:是,0:否"/]--]
	[@b.radios label="编辑状态"  name="collectSwitch.editable" value=collectSwitch.editable items="1:可编辑,0:不可编辑"/]
	[@b.radios label="必填状态"  name="collectSwitch.required" value=collectSwitch.required items="1:必填,0:非必填"/]
	[@b.radios label="是否启用"  name="collectSwitch.enabled" value=collectSwitch.enabled items="1:启用,0:禁用"/]
	[#-- 20201106增加是否取消宿舍功能 begin --]
	[#if collectSwitch.code = 'G042']
	[@b.radios label="是否可取消宿舍"  name="isAdflag" value=isAdflag items="1:启用,0:禁用"/]
	[/#if]
	[#-- 20201106增加是否取消宿舍功能 end --]
	[@b.formfoot]
    <input type="hidden" name="collectSwitch.id" value="${collectSwitch.id!}" />
		[@b.redirectParams/]
		[@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
	[/@]
[/@]
[@b.foot/]