[#ftl]
[@b.head/]
[@b.form name="footLinkSearchForm"  action="!search" target="footLinklist" title="ui.searchForm" theme="search"]
    [@b.textfields names="footLink.name;名称"/]
    [@b.select label="链接组" name="footLink.group.id" items=groups/]
    [@b.select name="footLink.enabled" label="状态" value="" empty="..." items={'1':'启用','0':'禁用'}/]
[/@]
[@b.div id="footLinklist" href="!search" /]
[@b.foot/]