[#ftl]
[@b.head/]
[@b.form name="studentSearchForm"  action="!search" target="studentlist" title="ui.searchForm" theme="search"]
    [@b.textfield label="年级" name="student.grade" value=year/]
    [@b.textfield label="学号" name="student.code"/]
    [@b.textfield label="姓名" name="student.name"/]
[/@]
[@b.div id="studentlist" href="!search?student.year=${year}" /]
[@b.foot/]