[#ftl]
[@b.head/]
[@b.grid  id="studentTable" items=students var="student" configs=listConfig]
	[@b.gridbar title="学生列表"]
	    bar.addItem("上传",action.edit());
    	bar.addItem("批量导入",action.method("importForm"));
	    bar.addItem("导出",action.method("export", null, null, false));
	[/@]
	[@b.row]
		[@b.boxcol/]
		[@b.col property="department.name" title="院系"/]
		[@b.col property="major.name" title="专业"/]
		[@b.col property="adminClass.name" title="班级"/]
		[@b.col property="code" title="学号"]
			[@b.a href="!info?student.id=${student.id!}"]${(student.code)!}[/@]
		[/@]
		[@b.col property="name" title="姓名"]
			[@b.a href="!info?student.id=${student.id!}"]${(student.name)!}[/@]
		[/@]
		[@b.col property="gender.name" align="center" title="性别"/]
		[@b.col property="grade" title="年级"/]
		[@b.col property="photo" title="是否有照片" align="center"]
			[@c.boolean student.photo??/]
		[/@]
	[/@]
[/@]
[@b.foot/]