[#ftl]
[@b.head/]
[@b.toolbar title=(b.text("department")+"信息") entityId=department.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="list"]
    [@b.textfield name="department.code" value="${department.code!}" required="true" maxlength="100" /]
    [@b.textfield name="department.name" value="${department.name!}" required="true" maxlength="100" /]
    [@b.textfield name="department.nameEn" value="${department.nameEn!}" maxlength="100" /]
    [#if b.text("department.departmentType.enabled") == "true"]
        [@b.select label="department.departmentType.name" name="department.departmentType.id" value=(department.departmentType.id)! required="true" items=departmentTypes option="id,name" empty="请选择..."/]
    [/#if]
    [@b.radios label="是否可用"  name="department.enabled" value=department.enabled items="1:是,0:否"/]
    [@b.formfoot]
        [@b.reset/]&nbsp;&nbsp;
        [@b.submit value="action.submit" /]
        [@b.redirectParams/]
    <input type="hidden" name="department.id" value="${department.id!}"/>
    [/@]
[/@]
[@b.foot/]