[#ftl]
[@b.head/]
[@b.form action="!search" title="ui.searchForm" target="departmentList" theme="search"]
    [@b.textfields names="department.code"/]
    [@b.textfields names="department.name"/]
    [#--[@b.textfields names="department.nameEn"/]--]
    [#--[#if b.text("department.departmentType.enabled") == "true"]--]
        [#--[@b.select name="department.departmentType.id" label="department.departmentType.name" items=departmentTypes/]--]
    [#--[/#if]--]
    [@b.select name="department.enabled" label="是否可用" items={'1':'是','0':'否'}/]
[/@]
[@b.div href="!search?orderBy=department.code" id="departmentList" class="dataList"/]
[@b.foot/]
