[#ftl]
[@b.head/]
[@b.toolbar title="部门院系"]bar.addBack();[/@]
[@b.form action="!save" title="部门院系信息" theme="info"]
	[@b.textfield label="院系编号" name="department.code" value="${department.code!}" /]
	[@b.textfield label="院系名称" name="department.name" value="${department.name!}" /]
	[@b.textfield label="院系英文名" name="department.nameEn" value="${department.nameEn!}"/]
	[@b.textfield label="院系类型" name="department.departmentType.name" value="${(department.departmentType.name)!}"/]
    [@b.radios label="是否可用"  name="department.enabled" value=department.enabled items="1:是,0:否"/]	
[/@]
[@b.foot/]