[#ftl]
[@b.head/]
[@b.form action="!search" title="ui.searchForm" target="majorList" theme="search"]
    [@b.textfields names="major.code;专业代码"/]
    [@b.textfields names="major.name;专业名称"/]
    [@b.select name="major.department.id" label="所属${b.text('department')}" items=departments?sort_by("code")/]
    [@b.select name="major.education.id" label="学历层次" items=educations?sort_by("code")/]
    [@b.select name="major.enabled" label="是否可用" items={'1':'是','0':'否'}/]
[/@]
[@b.div href="!search" id="majorList" class="dataList"/]
[@b.foot/]
