[#ftl]
[@b.head/]
[@b.form name="columnSearchForm"  action="!search" target="columnlist" title="ui.searchForm" theme="search"]
    [#--[@b.select label="栏目级别" name="column.level.id" items=levels/]--]
    [@b.select label="一级栏目" name="column.parent.id" items=topColumns/]
    [@b.textfields names="column.name;名称"/]
    [@b.select name="column.enabled" label="状态" value="" empty="..." items={'1':'启用','0':'禁用'}/]
[/@]
[@b.div id="columnlist" href="!search" /]
[@b.foot/]