[#ftl]
[@b.head/]
[@b.grid  items=columns var="column"]
    [@b.gridbar]
	bar.addItem("${b.text("action.new")}",action.add());
	bar.addItem("${b.text("action.modify")}",action.edit());
	bar.addItem("${b.text("action.delete")}",action.remove());
    [/@]
    [@b.row]
        [@b.boxcol/]
        [@b.col width="20%" property="code" title="排序" align="center"/]
        [@b.col width="20%" title="一级栏目" align="center"]
            [#if column.parent??]${(column.parent.name)!}[#else ]${(column.name)!}[/#if]
        [/@]
        [@b.col width="20%" title="二级栏目" align="center"]
            [#if column.parent??]${(column.name)!}[/#if]
        [/@]
        [@b.col width="20%" property="type.name" title="栏目类型" align="center"/]
        [@b.col width="20%" property="enabled" title="状态" align="center"]
            [@c.enabled column.enabled/]
        [/@]
    [/@]
[/@]
[@b.foot/]