[#ftl]
[@b.head/]
[@b.form name="studentEducationSearchForm"  action="!search?orderBy=student.code" target="studentEducationList" title="ui.searchForm" theme="search"]
    [@b.textfield label="年份" name="studentEducation.student.grade" value=year/]
    [@b.textfield label="学号" name="studentEducation.student.code"/]
    [@b.textfield label="姓名" name="studentEducation.student.name"/]
[/@]
[@b.div id="studentEducationList" href="!search?studentEducation.grade=${year}&orderBy=student.code" /]
[@b.foot/]