[#ftl]
[@b.head/]
[@b.grid  items=studentEducations var="studentEducation"]
    [@b.gridbar]
    bar.addItem("导出",action.exportData("student.code:考生号,student.name:学生姓名,student.enrollType.name:招生类别,student.major.name:专业,startDate:开始日期,endDate:结束日期,unit:在何地何学校,post:任何职,reterence:证明人", null,"&fileName=studentEducation"));
    [/@]

    [@b.row align="center"]
        [@b.boxcol width="1"/]
        [@b.col title="考生号" property="student.code"/]
        [@b.col title="学生姓名" property="student.name"/]
        [@b.col title="开始日期" property="startDate"/]
        [@b.col title="结束日期" property="endDate"/]
        [@b.col title="在何地何学校" property="unit"/]
        [@b.col title="任何职" property="post"/]
        [@b.col title="证明人" property="reterence"/]
    [/@]
[/@]
[@b.foot/]