[#ftl]
[@b.head/]
[@b.toolbar title="服装尺码" entityId=clothesSize.id!0]bar.addBack();[/@]
[@b.form action="!save" theme="form"]
    [@b.textfield label="代码" name="clothesSize.code" value="${clothesSize.code!}" required="true" maxlength="30"/]
    [@b.textfield label="尺码" name="clothesSize.name" value="${clothesSize.name!}" required="true" maxlength="30"/]
    [@b.textfield label="身高" name="clothesSize.height" value="${clothesSize.height!}" required="true" maxlength="30"/]
    [@b.textfield label="胸围" name="clothesSize.bust" value="${clothesSize.bust!}" required="true" maxlength="30"/]
    [@b.textfield label="腰围" name="clothesSize.waist" value="${clothesSize.waist!}" required="true" maxlength="30"/]
    [@b.textfield label="臀围" name="clothesSize.hip" value="${clothesSize.hip!}" required="true" maxlength="30"/]
    [@b.textfield label="裤长" name="clothesSize.outseam" value="${clothesSize.outseam!}" required="true" maxlength="30"/]
    [@b.formfoot]
	<input type="hidden" name="clothesSize.id" value="${clothesSize.id!}"/>
        [@b.redirectParams/]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
[/@]
[@b.foot/]