[#ftl]
[@b.head/]
[@b.grid  items=clothesSizes var="clothesSize"]
    [@b.gridbar]
	bar.addItem("新建",action.add());
	bar.addItem("修改",action.edit());
	bar.addItem("删除",action.remove());
    [/@]
    [@b.row]
        [@b.boxcol width="1"/]
        [@b.col title="代码" property="code" align="center"/]
        [@b.col title="尺码" property="name" align="center"/]
        [@b.col title="身高" property="height" align="center"/]
        [@b.col title="胸围" property="bust" align="center"/]
        [@b.col title="腰围" property="waist" align="center"/]
        [@b.col title="臀围" property="hip" align="center"/]
        [@b.col title="裤长" property="outseam" align="center"/]
    [/@]
[/@]
[@b.foot/]