[#ftl]
[@b.head/]
[@b.grid  items=collectSwitchStateViews var="collectSwitchStateView"]
    [@b.gridbar]
	bar.addItem("统计",action.method("count"));
    [/@]
    [@b.row align="center"]
        [#--[@b.boxcol/]--]
        [@b.col title="学院" property="student.department.name"/]
        [@b.col title="专业" property="student.major.name"/]
        [@b.col title="班级" property="student.adminClass.name"/]
        [@b.col title="学号" property="student.code"]
            [#--[@b.a href="!info?id=${collectSwitchStateView.id}"]${(collectSwitchStateView.student.code)!}[/@]--]
            ${(collectSwitchStateView.student.code)!}
        [/@]
        [@b.col title="姓名" property="student.name" /]
        [@b.col title="性别" property="student.gender.name"/]
        [@b.col title="采集项目" property="collectSwitch.name"/]
        [@b.col title="是否填写" property="state.finished" sortable="false"]
            [@c.boolean (collectSwitchStateView.state.finished)!false/]
        [/@]
    [/@]
[/@]
[@b.foot/]