[#ftl]
[@b.head/]
[@b.toolbar title="${(classAccomPlan.adminClass.name)!}-${(classAccomPlan.dormPlan.gender)!}已安排床位"]bar.addBack();[/@]
[@b.grid  items=dormPlanBeds var="dormPlanBed" sortable="true"]
    [@b.gridbar]
    [/@]
    [@b.row]
        [@b.col title="床位编号" property="bed.code" align="center"/]
        [@b.col title="床位号" property="bed.name" align="center"/]
        [@b.col title="宿舍楼" property="bed.room.building.name" align="center"/]
        [@b.col title="寝室" property="bed.room.name" align="center"/]
        [@b.col title="面向性别" property="bed.room.gender" align="center"/]
        [@b.col title="租金" property="bed.room.rent" align="center"/]
        [@b.col title="学号" property="student.code" align="center"/]
		[@b.col title="姓名" property="student.name" align="center" align="center"/]
		[@b.col title="班级" property="student.adminClass.name" align="center" align="center"/]
    [/@]
[/@]
[@b.foot/]