[#ftl]
[@b.head/]
[@b.toolbar title="${(classAccomPlan.adminClass.name)!}--${(classAccomPlan.gender)!}生住宿学生名单"]bar.addBack();[/@]
[@b.grid  items=dormStudents var="dormStudent"]
	[@b.gridbar]
		 bar.addItem("床位分配",action.multi("allocStdBed","","&classAccomPlan.id=${(classAccomPlan.id)!}"),"fa-edit","blue");
		 bar.addItem("取消分配",action.multi("allocCancle", "是否确定取消选择的床位分配？","&classAccomPlan.id=${(classAccomPlan.id)!}"),"fa-remove","red");
	[/@]
	[@b.row]
		[@b.boxcol/]
		[@b.col title="学号" property="student.code" align="center"/]
		[@b.col title="姓名" property="student.name" align="center" align="center"/]
		[@b.col title="性别" property="student.gender.name" align="center"/]
		[@b.col title="年级" property="student.grade" align="center"/]
		[@b.col title="学院" property="student.department.name" align="center"/]
		[@b.col title="班级" property="student.adminClass.name" align="center"/]
		[@b.col title="学历层次" property="student.education.name" align="center"/]
		[@b.col title="入学年月" property="student.enrollmentDate" align="center"/]
		[@b.col title="校区" property="student.campus.name" align="center"/]
		[@b.col title="宿舍" property="planBed.bed.room.code" align="center"/]
		[@b.col title="床位" property="planBed.bed.name" align="center"/]
		[@b.col title="租金" property="planBed.bed.room.rent" align="center"/]
		[@b.col title="是否完成" property="finished" align="center"][@c.boolean dormStudent.finished "已完成" "未完成"/][/@]
	[/@]
[/@]
[@b.foot/]