[#ftl]
[#include "/template/list/comm.ftl"]	
[@b.head/]
[@b.toolbar title="班级住宿计划"]bar.addBack();[/@]
[@b.form theme="info"]
 	[@b.textfield label="年份" value="${(classAccomPlan.dormPlan.year)!}"/]
 	[@b.textfield label="计划名称" value="${(classAccomPlan.dormPlan.name)!}"/]
    [@b.textfield label="班级代码" value="${(classAccomPlan.adminClass.code)!}"/]
    [@b.textfield label="班级名称" value="${(classAccomPlan.adminClass.name)!}"/]
    [@b.textfield label="院（系）代码" value="${(classAccomPlan.adminClass.department.code)!}"/]
    [@b.textfield label="院（系）名称" value="${(classAccomPlan.adminClass.department.name)!}"/]
    [@b.textfield label="寝室面向性别" value="${(classAccomPlan.gender)!}"/]
    [@b.textfield label="计划人数" value="${(classAccomPlan.planNum)!}"/]
    [@b.textfield label="安排床位数" value="${(classAccomPlan.allotNum)!}"/]
    [@b.textfield label="已安排学生" value="${(classAccomPlan.allotNum)!}"/]
    [@b.textfield label="备注" value="${(classAccomPlan.remark)!}"/]
[/@]
[@b.foot/]