[#ftl]
[@b.head/]
[@b.form name="financeStudentViewSearchForm"  action="!search?orderBy=financeStudentView.student.code" target="financeStudentViewlist" title="ui.searchForm" theme="search"]
    [@b.textfield label="年份" name="financeStudentView.student.grade" value=year/]
    [@b.textfield label="学号" name="financeStudentView.student.code"/]
    [@b.textfield label="姓名" name="financeStudentView.student.name"/]
    [@b.select label="缴费状态" name="status" items={'1':'已缴费','3':'未缴费'}/]
    [#--[@b.select label="缴费状态" name="status" items={'1':'交清','2':'部分交清','3':'未交清'}/]--]
[/@]
[@b.div id="financeStudentViewlist" href="!search?financeStudentView.student.grade=${year}&orderBy=financeStudentView.student.code" /]
[@b.foot/]